Added Roadmap.md and git essentials.md
saucam/bootcamp pull request #1
Opened 2024-02-04 10:28 UTC by MadhavGoswami

2024-02-04 13:35 UTC, saucam commented on git-essentials.md
> +2. git clone "https:....."
You should put the commands within triple quotes so they display as commands 

```
git clone <repo url>
```

2024-02-04 13:37 UTC, saucam commented on git-essentials.md
> +Some other commands to work in terminal
These should go in a separate file 
you can name it terminal.md
title can be working with unix terminal

2024-02-04 13:38 UTC, saucam commented
Thanks for this work! I have minor comments to improve the formatting. Please fix them and then we can merge

2024-02-04 13:43 UTC, saucam requested changes
Thanks for this work! You can also add markdown.md file (put some markdown basics there) and terminal.md file as explained in one of the other comments. I also have some minor comments to improve the formatting. Please fix them and then we can merge

2024-02-04 16:26 UTC, MadhavGoswami commented
Check the new commits the formatting is fixed, commands are added and a separate file Terminal.md is created

2024-02-04 16:57 UTC, MadhavGoswami commented
Markdown basics md is also added.

2024-02-05 02:57 UTC, saucam approved these changes

2024-02-05 02:58 UTC, saucam commented
Excellent work ! Lgtm

2024-02-05 02:58 UTC, merged